export const FORM_ACTION_TYPES = {
  CHANGE_INPUT: "CHANGE_INPUT",
};

export const PROCESS_ACTION_TYPES = {
  FETCH_START: "FETCH_START",
  FETCH_SUCCESS: "FETCH_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
};
